steps:
  # Step 1: Build the container image using Jib
  - name: 'gcr.io/cloud-builders/gradle'
    args:
      - 'jib'
      - '--image=gcr.io/$PROJECT_ID/$IMAGE_NAME'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$SERVICE_NAME'
      - '--image=gcr.io/$PROJECT_ID/$IMAGE_NAME'
      - '--region=$REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _IMAGE_NAME: 'spring-rest-test'
  _SERVICE_NAME: 'spring-rest-test'
  _REGION: 'us-central1'

timeout: '1200s'
